# Generated by Django 5.1.2 on 2024-11-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('like', 'Like'), ('save', 'Save'), ('comment', 'Comment'), ('share', 'Share'), ('set_today_song', 'Set Today Song')], max_length=20),
        ),
    ]
