# Generated by Django 5.1.1 on 2024-10-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_liked_songs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/이력서_사진.jpg', upload_to='profile_pics/'),
        ),
    ]
