# Generated by Django 5.1.2 on 2024-10-16 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("musics", "0007_alter_song_album_cover"),
        ("users", "0003_alter_userprofile_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="liked_songs",
            field=models.ManyToManyField(
                blank=True, related_name="liked_by_user", to="musics.song"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(default="test-user", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, default="profile_pics/이력서_사진.jpg", upload_to="profile_pics/"
            ),
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
