# Generated by Django 5.1.2 on 2024-11-01 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0002_initial'),
        ('users', '0004_alter_friendrequest_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('like', 'Like'), ('save', 'Save'), ('share', 'Share'), ('set_today_song', 'Set Today Song')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('friend_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friend_activities', to=settings.AUTH_USER_MODEL)),
                ('song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_activities', to='musics.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
