# Generated by Django 5.1.2 on 2024-11-06 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_useractivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='today_song',
        ),
    ]
