version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: muze
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: silver
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  redis:
    image: redis:6.2
    restart: always
    networks:
      - app_network

  django:
    build:
      context: .
      dockerfile: Dockerfile  # Dockerfile 경로를 설정
    restart: always
    environment:
      DATABASE_URL: mysql://silver:password@db/muze
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis
      - migrations
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - app_network

  migrations:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
        sh -c ". /app/.venv/bin/activate && 
        python manage.py migrate && python manage.py collectstatic --noinput"
    environment:
      DATABASE_URL: mysql://silver:password@db/muze
    volumes:
      - .:/app
  
  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    ports:
      - "9090:9090"
    networks:
      - app_network

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "3000:3000"
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
