version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env.docker
    environment:
      MYSQL_DATABASE: muze
      MYSQL_USER: silver
      MYSQL_ROOT_PASSWORD: dmstjd6918
      MYSQL_PASSWORD: dmstjd6918
      DB_PORT: 3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network
    ports:
      - "3306:3306"

  redis:
    image: redis:6.2
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app_network


  django:
    build:
      context: .
      dockerfile: Dockerfile  # Dockerfile 경로를 설정
    restart: always
    environment:
      DOCKER_ENV: 'true'
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis

    command: >
      bash -c "
      chmod + ./wait-for-it.sh &&
      ./wait-for-it.sh db:3306 -t 10 &&
      sh run.sh"
  
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - app_network

  # MongoDB for Graylog
  mongo:
    image: mongo:4.0
    restart: always
    networks:
      - app_network
    volumes:
      - mongo_data:/data/db

  # Elasticsearch for Graylog
  elasticsearch:
    image: elasticsearch:7.10.1
    restart: always
    environment:
      - discovery.type=single-node
    networks:
      - app_network
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  # Graylog
  graylog:
    image: graylog/graylog:4.0
    restart: always
    environment:
      - GRAYLOG_PASSWORD_SECRET=8c6027627521dfbf64bcb25a93db8b8289f6ad13ca77bc89dc798b572bf82c31
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://localhost:9000/
    ports:
      - "9000:9000"
      - "12201:12201"  # Graylog input
    networks:
      - app_network
    depends_on:
      - mongo
      - elasticsearch

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"  # RabbitMQ 관리 콘솔
    networks:
      - app_network

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A music_dashboard worker --loglevel=info
    depends_on:
      - django
      - rabbitmq
    volumes:
      - .:/app
    networks:
      - app_network

volumes:
  db_data:
  mongo_data:
  elasticsearch_data:

networks:
  app_network:
