# Generated by Django 5.1.2 on 2024-10-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('track_popularity', models.IntegerField(default=0)),
                ('album_cover', models.URLField()),
                ('artist', models.CharField(max_length=100)),
                ('genre', models.CharField(blank=True, choices=[('POP', 'Pop'), ('ROCK', 'Rock'), ('HIPHOP', 'Hip Hop'), ('R&B', 'R&B'), ('JAZZ', 'Jazz'), ('CLASSICAL', 'Classical'), ('COUNTRY', 'Country'), ('REGGAE', 'Reggae'), ('ELECTRONIC', 'Electronic'), ('METAL', 'Metal')], max_length=20)),
                ('release_date', models.DateField()),
                ('num_mention', models.IntegerField(default=0)),
                ('num_likes', models.IntegerField(default=0)),
            ],
        ),
    ]
