# Generated by Django 5.1.2 on 2024-11-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'musics_comment',
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='음악 제목', max_length=200)),
                ('track_popularity', models.IntegerField(default=0, help_text='음악 인기도')),
                ('album_cover', models.URLField(help_text='앨범 커버 이미지 URL')),
                ('album_name', models.CharField(help_text='앨범 이름', max_length=200)),
                ('artists', models.CharField(help_text='아티스트', max_length=100)),
                ('genre', models.CharField(blank=True, choices=[('POP', 'Pop'), ('ROCK', 'Rock'), ('HIPHOP', 'Hip Hop'), ('R&B', 'R&B'), ('JAZZ', 'Jazz'), ('CLASSICAL', 'Classical'), ('COUNTRY', 'Country'), ('REGGAE', 'Reggae'), ('ELECTRONIC', 'Electronic'), ('METAL', 'Metal')], help_text='장르', max_length=20)),
                ('release_date', models.DateField(help_text='발매일')),
                ('num_mention', models.IntegerField(default=0)),
                ('num_likes', models.IntegerField(default=0)),
                ('spotify_url', models.URLField()),
            ],
            options={
                'db_table': 'musics_song',
                'ordering': ['-release_date', 'title'],
                'get_latest_by': 'release_date',
                'abstract': False,
                'managed': True,
                'proxy': False,
            },
        ),
        migrations.CreateModel(
            name='TodaySong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'musics_today_song',
            },
        ),
    ]
