# Generated by Django 5.1.2 on 2024-11-14 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='musics.song'),
        ),
        migrations.AddField(
            model_name='todaysong',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musics.song'),
        ),
        migrations.AddField(
            model_name='todaysong',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='today_song_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
