# Generated by Django 5.1.1 on 2024-10-15 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("musics", "0003_alter_song_album_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="album_cover",
            field=models.ImageField(
                default="default_albumcover.png",
                max_length=200,
                upload_to="album_cover/",
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="genre",
            field=models.CharField(
                blank=True,
                choices=[
                    ("POP", "Pop"),
                    ("ROCK", "Rock"),
                    ("HIPHOP", "Hip Hop"),
                    ("R&B", "R&B"),
                    ("JAZZ", "Jazz"),
                    ("CLASSICAL", "Classical"),
                    ("COUNTRY", "Country"),
                    ("REGGAE", "Reggae"),
                    ("ELECTRONIC", "Electronic"),
                    ("METAL", "Metal"),
                ],
                max_length=20,
            ),
        ),
    ]
