# Generated by Django 5.1.2 on 2024-11-06 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0005_alter_todaysong_song'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='todaysong',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musics.song'),
        ),
        migrations.AlterField(
            model_name='todaysong',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='today_song_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
