# Generated by Django 5.1.1 on 2024-10-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0005_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='num_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='num_mention',
            field=models.IntegerField(default=0),
        ),
    ]
