# Generated by Django 5.1.1 on 2024-10-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0006_song_num_likes_song_num_mention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album_cover',
            field=models.URLField(),
        ),
    ]
