# Generated by Django 5.1.2 on 2024-11-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("musics", "0006_alter_todaysong_song_alter_todaysong_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="song",
            old_name="album",
            new_name="album_name",
        ),
        migrations.RenameField(
            model_name="song",
            old_name="artist",
            new_name="artists",
        ),
        migrations.AddField(
            model_name="song",
            name="spotify_url",
            field=models.URLField(default="None"),
            preserve_default=False,
        ),
    ]
